name: deploy

on:
  push:
    branches:
      - main 
  pull_request:
    types:
      - closed
    branches:
      - main
      
jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Deploy to EC2
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ubuntu
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            cd /home/ubuntu/fastapi-book-project
            git pull origin main
            source /home/ubuntu/fastapi-book-project/venv/bin/activate  
            pip install -r requirements.txt               
            sudo systemctl restart fastapi
            sudo systemctl restart nginx
